### PR TITLE
added a docstring to explain the save function in bookstore

### PR DESCRIPTION
**Pull request by mkhalil7625**
@Jake-Fischer

### CODE REVIEW

**Review by Jake-Fischer — CHANGES_REQUESTED** [review]
Looking good! I am able to understand what the save function is doing just from reading the docstring. 

I made a few edits in my post below that I think make it a little more clear how save is interacting and using the database. I also got rid of the reference to 'Create_book' because I think it would be better to use _add_book, I don't see a 'Create_book'. Let me know what you think,

There are also a few small typos and a little grammar I would fix, Ill fix them in the following paragraph so you can copy and paste if it is looking good to you. 

"""
        When called, checks if an ID of a book was entered. 
        If the user entered a valid ID, the save function will call
        the _update_book function to update the database record for that book.
        If an ID was passed that does not exist in the database, it will call the _add_book 
        function which will create a new book record and assign the next available ID to the new 
        book record.
"""

**Comment by mkhalil7625** [comment]
@Jake-Fischer 
I used your verbiage with the except of "If an ID was passed that does not exist in the database," the save function is being utilized in different operations. when we want to create a new book, no ID is passed into the save function.

**Comment by Jake-Fischer** [comment]
You're totally right, thanks for catching that. I'll go ahead and merge!

**Comment by claraj** [comment]
Looks good. Even though spelling and grammar are not part of the code, it's important to use correct spelling and good grammar in your documentation. Thanks!

**Pull request merged**
